apiVersion: v1
entries:
  java-service:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-27T12:38:24.412349416Z"
    description: Common Helm chart for all Java microservices
    digest: 72d97038db3ffb00b74e1a6868ef49ccd019ae16c65a0a1d0c39a3b124ba83d5
    name: java-service
    type: application
    urls:
    - https://funmagsoft.github.io/helm/charts/java-service-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-27T12:38:24.411980816Z"
