apiVersion: v1
entries:
  java-service:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-24T17:41:43.037630109Z"
    description: Common Helm chart for all Java microservices
    digest: 8ede4ffa0b1c804277ed854f9597aa7c02609f7797cdf3ac27bf118a15d3f644
    name: java-service
    type: application
    urls:
    - https://funmagsoft.github.io/helm/charts/java-service-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-24T17:41:43.037287397Z"
