apiVersion: v1
entries:
  java-service:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-24T20:30:28.374035805Z"
    description: Common Helm chart for all Java microservices
    digest: 71e5b5cd18b246b1e277aca8ff8a2173ca4257e4fb76ba20382e1104ad7d8e09
    name: java-service
    type: application
    urls:
    - https://funmagsoft.github.io/helm/charts/java-service-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-24T20:30:28.373692895Z"
