apiVersion: v1
entries:
  java-service:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-11-26T08:21:01.855264302Z"
    description: Common Helm chart for all Java microservices
    digest: 4ed315e5d9533441efc733b60dc2b526296fa2ce9909aa7286fbefa6e37f352e
    name: java-service
    type: application
    urls:
    - https://funmagsoft.github.io/helm/charts/java-service-1.0.0.tgz
    version: 1.0.0
generated: "2025-11-26T08:21:01.854949483Z"
